### ISSUE TITLE
ascii

### ISSUE THREAD

**Issue by qizq1337** [Lodisus/MultiToolV2#2]
how would i make my own ascii (instead of multitool) i want it to be smthing else with the blue theme

pls tell or sus

**Comment by Lodisus** [comment]
http://www.patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=lol

**Comment by qizq1337** [comment]
> http://www.patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=lol

hallo yes i know that but how to do all the fore color's is there any way to do it automatically

**Comment by Lodisus** [comment]
replied in discord dm
